In [1]:
import pandas as pd
import numpy as np

In [6]:
test1 = pd.read_excel('sales_data_sample.xlsx')

In [7]:
test1.head()

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,QTR_ID,MONTH_ID,YEAR_ID,...,ADDRESSLINE1,ADDRESSLINE2,CITY,STATE,POSTALCODE,COUNTRY,TERRITORY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE
0,10107,30,95.70,2,2871.00,2003-02-24,Shipped,1,2,2003,...,897 Long Airport Avenue,NaN,NYC,NY,10022,USA,NaN,Yu,Kwai,Small
1,10121,34,81.35,5,2765.90,2003-05-07,Shipped,2,5,2003,...,59 rue de l'Abbaye,NaN,Reims,NaN,51100,France,EMEA,Henriot,Paul,Small
2,10134,41,94.74,2,3884.34,2003-07-01,Shipped,3,7,2003,...,27 rue du Colonel Pierre Avia,NaN,Paris,NaN,75508,France,EMEA,Da Cunha,Daniel,Medium
3,10145,45,83.26,6,3746.70,2003-08-25,Shipped,3,8,2003,...,78934 Hillside Dr.,NaN,Pasadena,CA,90003,USA,NaN,Young,Julie,Medium
4,10159,49,100.00,14,5205.27,2003-10-10,Shipped,4,10,2003,...,7734 Strong St.,NaN,San Francisco,CA,NaN,USA,NaN,Brown,Julie,Medium

In [8]:
test1.tail()

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,QTR_ID,MONTH_ID,YEAR_ID,...,ADDRESSLINE1,ADDRESSLINE2,CITY,STATE,POSTALCODE,COUNTRY,TERRITORY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE
2818,10350,20,100.00,15,2244.40,2004-12-02,Shipped,4,12,2004,...,"C/ Moralzarzal, 86",NaN,Madrid,NaN,28034,Spain,EMEA,Freyre,Diego,Small
2819,10373,29,100.00,1,3978.51,2005-01-31,Shipped,1,1,2005,...,Torikatu 38,NaN,Oulu,NaN,90110,Finland,EMEA,Koskitalo,Pirkko,Medium
2820,10386,43,100.00,4,5417.57,2005-03-01,Resolved,1,3,2005,...,"C/ Moralzarzal, 86",NaN,Madrid,NaN,28034,Spain,EMEA,Freyre,Diego,Medium
2821,10397,34,62.24,1,2116.16,2005-03-28,Shipped,1,3,2005,...,1 rue Alsace-Lorraine,NaN,Toulouse,NaN,31000,France,EMEA,Roulet,Annette,Small
2822,10414,47,65.52,9,3079.44,2005-05-06,On Hold,2,5,2005,...,8616 Spinnaker Dr.,NaN,Boston,MA,51003,USA,NaN,Yoshido,Juri,Medium

In [10]:
test1.shape[]

SyntaxError: invalid syntax (<ipython-input-10-4f6caf0f6830>, line 1)

In [11]:
pd.set_option('display.max_rows', 100)
test1

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,QTR_ID,MONTH_ID,YEAR_ID,...,ADDRESSLINE1,ADDRESSLINE2,CITY,STATE,POSTALCODE,COUNTRY,TERRITORY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE
0,10107,30,95.70,2,2871.00,2003-02-24,Shipped,1,2,2003,...,897 Long Airport Avenue,NaN,NYC,NY,10022,USA,NaN,Yu,Kwai,Small
1,10121,34,81.35,5,2765.90,2003-05-07,Shipped,2,5,2003,...,59 rue de l'Abbaye,NaN,Reims,NaN,51100,France,EMEA,Henriot,Paul,Small
2,10134,41,94.74,2,3884.34,2003-07-01,Shipped,3,7,2003,...,27 rue du Colonel Pierre Avia,NaN,Paris,NaN,75508,France,EMEA,Da Cunha,Daniel,Medium
3,10145,45,83.26,6,3746.70,2003-08-25,Shipped,3,8,2003,...,78934 Hillside Dr.,NaN,Pasadena,CA,90003,USA,NaN,Young,Julie,Medium
4,10159,49,100.00,14,5205.27,2003-10-10,Shipped,4,10,2003,...,7734 Strong St.,NaN,San Francisco,CA,NaN,USA,NaN,Brown,Julie,Medium
5,10168,36,96.66,1,3479.76,2003-10-28,Shipped,4,10,2003,...,9408 Furth Circle,NaN,Burlingame,CA,94217,USA,NaN,Hirano,Juri,Medium
6,10180,29,86.13,9,2497.77,2003-11-11,Shipped,4,11,2003,...,"184, chausse de Tournai",NaN,Lille,NaN,59000,France,EMEA,Rance,Martine,Small
7,10188,48,100.00,1,5512.32,2003-11-18,Shipped,4,11,2003,...,"Drammen 121, PR 744 Sentrum",NaN,Bergen,NaN,N 5804,Norway,EMEA,Oeztan,Veysel,Medium
8,10201,22,98.57,2,2168.54,2003-12-01,Shipped,4,12,2003,...,5557 North Pendale Street,NaN,San Francisco,CA,NaN,USA,NaN,Murphy,Julie,Small
9,10211,41,100.00,14,4708.44,2004-01-15,Shipped,1,1,2004,...,"25, rue Lauriston",NaN,Paris,NaN,75016,France,EMEA,Perrier,Dominique,Medium
10,10223,37,100.00,1,3965.66,2004-02-20,Shipped,1,2,2004,...,636 St Kilda Road,Level 3,Melbourne,Victoria,3004,Australia,APAC,Ferguson,Peter,Medium
11,10237,23,100.00,7,2333.12,2004-04-05,Shipped,2,4,2004,...,2678 Kingston Rd.,Suite 101,NYC,NY,10022,USA,NaN,Frick,Michael,Small
12,10251,28,100.00,2,3188.64,2004-05-18,Shipped,2,5,2004,...,7476 Moss Rd.,NaN,Newark,NJ,94019,USA,NaN,Brown,William,Medium
13,10263,34,100.00,2,3676.76,2004-06-28,Shipped,2,6,2004,...,25593 South Bay Ln.,NaN,Bridgewater,CT,97562,USA,NaN,King,Julie,Medium
14,10275,45,92.83,1,4177.35,2004-07-23,Shipped,3,7,2004,...,"67, rue des Cinquante Otages",NaN,Nantes,NaN,44000,France,EMEA,Labrune,Janine,Medium
15,10285,36,100.00,6,4099.68,2004-08-27,Shipped,3,8,2004,...,39323 Spinnaker Dr.,NaN,Cambridge,MA,51247,USA,NaN,Hernandez,Marta,Medium
16,10299,23,100.00,9,2597.39,2004-09-30,Shipped,3,9,2004,...,Keskuskatu 45,NaN,Helsinki,NaN,21240,Finland,EMEA,Karttunen,Matti,Small
17,10309,41,100.00,5,4394.38,2004-10-15,Shipped,4,10,2004,...,Erling Skakkes gate 78,NaN,Stavern,NaN,4110,Norway,EMEA,Bergulfsen,Jonas,Medium
18,10318,46,94.74,1,4358.04,2004-11-02,Shipped,4,11,2004,...,7586 Pompton St.,NaN,Allentown,PA,70267,USA,NaN,Yu,Kyung,Medium
19,10329,42,100.00,1,4396.14,2004-11-15,Shipped,4,11,2004,...,897 Long Airport Avenue,NaN,NYC,NY,10022,USA,NaN,Yu,Kwai,Medium
20,10341,41,100.00,9,7737.93,2004-11-24,Shipped,4,11,2004,...,Geislweg 14,NaN,Salzburg,NaN,5020,Austria,EMEA,Pipps,Georg,Large
21,10361,20,72.55,13,1451.00,2004-12-17,Shipped,4,12,2004,...,"Monitor Money Building, 815 Pacific Hwy",Level 6,Chatswood,NSW,2067,Australia,APAC,Huxley,Adrian,Small
22,10375,21,34.91,12,733.11,2005-02-03,Shipped,1,2,2005,...,"67, rue des Cinquante Otages",NaN,Nantes,NaN,44000,France,EMEA,Labrune,Janine,Small
23,10388,42,76.36,4,3207.12,2005-03-03,Shipped,1,3,2005,...,1785 First Street,NaN,New Bedford,MA,50553,USA,NaN,Benitez,Violeta,Medium
24,10403,24,100.00,7,2434.56,2005-04-08,Shipped,2,4,2005,...,Berkeley Gardens 12 Brewery,NaN,Liverpool,NaN,WX1 6LT,UK,EMEA,Devon,Elizabeth,Small
25,10417,66,100.00,2,7516.08,2005-05-13,Disputed,2,5,2005,...,"C/ Moralzarzal, 86",NaN,Madrid,NaN,28034,Spain,EMEA,Freyre,Diego,Large
26,10103,26,100.00,11,5404.62,2003-01-29,Shipped,1,1,2003,...,Erling Skakkes gate 78,NaN,Stavern,NaN,4110,Norway,EMEA,Bergulfsen,Jonas,Medium
27,10112,29,100.00,1,7209.11,2003-03-24,Shipped,1,3,2003,...,Berguvsvâ€žgen 8,NaN,Lule,NaN,S-958 22,Sweden,EMEA,Berglund,Christina,Large
28,10126,38,100.00,11,7329.06,2003-05-28,Shipped,2,5,2003,...,"C/ Araquil, 67",NaN,Madrid,NaN,28023,Spain,EMEA,Sommer,MartÂ¡n,Large
29,10140,37,100.00,11,7374.10,2003-07-24,Shipped,3,7,2003,...,9408 Furth Circle,NaN,Burlingame,CA,94217,USA,NaN,Hirano,Juri,Large
30,10150,45,100.00,8,10993.50,2003-09-19,Shipped,3,9,2003,...,"Bronz Sok., Bronz Apt. 3/6 Tesvikiye",NaN,Singapore,NaN,79903,Singapore,Japan,Natividad,Eric,Large
31,10163,21,100.00,1,4860.24,2003-10-20,Shipped,4,10,2003,...,5905 Pompton St.,Suite 750,NYC,NY,10022,USA,NaN,Hernandez,Maria,Medium
32,10174,34,100.00,4,8014.82,2003-11-06,Shipped,4,11,2003,...,31 Duncan St. West End,NaN,South Brisbane,Queensland,4101,Australia,APAC,Calaghan,Tony,Large
33,10183,23,100.00,8,5372.57,2003-11-13,Shipped,4,11,2003,...,782 First Street,NaN,Philadelphia,PA,71270,USA,NaN,Cervantes,Francisca,Medium
34,10194,42,100.00,11,7290.36,2003-11-25,Shipped,4,11,2003,...,"2, rue du Commerce",NaN,Lyon,NaN,69004,France,EMEA,Saveley,Mary,Large
35,10206,47,100.00,6,9064.89,2003-12-05,Shipped,4,12,2003,...,1900 Oak St.,NaN,Vancouver,BC,V3F 2K1,Canada,NaN,Tannamuri,Yoshi,Large
36,10215,35,100.00,3,6075.30,2004-01-29,Shipped,1,1,2004,...,3675 Furth Circle,NaN,Burbank,CA,94019,USA,NaN,Thompson,Steve,Medium
37,10228,29,100.00,2,6463.23,2004-03-10,Shipped,1,3,2004,...,4658 Baden Av.,NaN,Cambridge,MA,51247,USA,NaN,Tseng,Kyung,Medium
38,10245,34,100.00,9,6120.34,2004-05-04,Shipped,2,5,2004,...,567 North Pendale Street,NaN,New Haven,CT,97823,USA,NaN,Murphy,Leslie,Medium
39,10258,32,100.00,6,7680.64,2004-06-15,Shipped,2,6,2004,...,2-2-8 Roppongi,NaN,Minato-ku,Tokyo,106-0032,Japan,Japan,Shimamura,Akiko,Large
40,10270,21,100.00,9,4905.39,2004-07-19,Shipped,3,7,2004,...,"Monitor Money Building, 815 Pacific Hwy",Level 6,Chatswood,NSW,2067,Australia,APAC,Huxley,Adrian,Medium
41,10280,34,100.00,2,8014.82,2004-08-17,Shipped,3,8,2004,...,Via Monte Bianco 34,NaN,Torino,NaN,10100,Italy,EMEA,Accorti,Paolo,Large
42,10291,37,100.00,11,7136.19,2004-09-08,Shipped,3,9,2004,...,?kergatan 24,NaN,Boras,NaN,S-844 67,Sweden,EMEA,Larsson,Maria,Large
43,10304,47,100.00,6,10172.70,2004-10-11,Shipped,4,10,2004,...,"67, avenue de l'Europe",NaN,Versailles,NaN,78000,France,EMEA,Tonini,Daniel,Large
44,10312,48,100.00,3,11623.70,2004-10-21,Shipped,4,10,2004,...,5677 Strong St.,NaN,San Rafael,CA,97562,USA,NaN,Nelson,Valarie,Large
45,10322,40,100.00,1,6000.40,2004-11-04,Shipped,4,11,2004,...,2304 Long Airport Avenue,NaN,Nashua,NH,62005,USA,NaN,Young,Valarie,Medium
46,10333,26,100.00,3,3003.00,2004-11-18,Shipped,4,11,2004,...,5557 North Pendale Street,NaN,San Francisco,CA,NaN,USA,NaN,Murphy,Julie,Medium
47,10347,30,100.00,1,3944.70,2004-11-29,Shipped,4,11,2004,...,636 St Kilda Road,Level 3,Melbourne,Victoria,3004,Australia,APAC,Ferguson,Peter,Medium
48,10357,32,100.00,10,5691.84,2004-12-10,Shipped,4,12,2004,...,5677 Strong St.,NaN,San Rafael,CA,97562,USA,NaN,Nelson,Valarie,Medium
49,10369,41,100.00,2,4514.92,2005-01-20,Shipped,1,1,2005,...,7825 Douglas Av.,NaN,Brickhaven,MA,58339,USA,NaN,Nelson,Allen,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2773,10143,37,50.65,10,1874.05,2003-08-10,Shipped,3,8,2003,...,4575 Hillside Dr.,NaN,New Bedford,MA,50553,USA,NaN,Tam,Wing C,Small
2774,10155,34,49.16,8,1671.44,2003-10-06,Shipped,4,10,2003,...,Keskuskatu 45,NaN,Helsinki,NaN,21240,Finland,EMEA,Karttunen,Matti,Small
2775,10167,40,41.71,4,1668.40,2003-10-23,Cancelled,4,10,2003,...,?kergatan 24,NaN,Boras,NaN,S-844 67,Sweden,EMEA,Larsson,Maria,Small
2776,10178,45,51.15,7,2301.75,2003-11-08,Shipped,4,11,2003,...,1 rue Alsace-Lorraine,NaN,Toulouse,NaN,31000,France,EMEA,Roulet,Annette,Small
2777,10186,28,52.14,4,1459.92,2003-11-14,Shipped,4,11,2003,...,120 Hanover Sq.,NaN,London,NaN,WA1 1DP,UK,EMEA,Hardy,Thomas,Small
2778,10197,29,41.71,1,1209.59,2003-11-26,Shipped,4,11,2003,...,"Rambla de CataluÂ¤a, 23",NaN,Barcelona,NaN,8022,Spain,EMEA,Saavedra,Eduardo,Small
2779,10209,48,44.69,3,2145.12,2004-01-09,Shipped,1,1,2004,...,6047 Douglas Av.,NaN,Los Angeles,CA,NaN,USA,NaN,Chandler,Michael,Small
2780,10222,31,45.69,7,1416.39,2004-02-19,Shipped,1,2,2004,...,361 Furth Circle,NaN,San Diego,CA,91217,USA,NaN,Thompson,Valarie,Small
2781,10249,32,57.61,3,1843.52,2004-05-08,Shipped,2,5,2004,...,4658 Baden Av.,NaN,Cambridge,MA,51247,USA,NaN,Tseng,Kyung,Small
2782,10262,21,57.11,12,1199.31,2004-06-24,Cancelled,2,6,2004,...,"C/ Moralzarzal, 86",NaN,Madrid,NaN,28034,Spain,EMEA,Freyre,Diego,Small
2783,10274,32,58.60,4,1875.20,2004-07-21,Shipped,3,7,2004,...,7825 Douglas Av.,NaN,Brickhaven,MA,58339,USA,NaN,Nelson,Allen,Small
2784,10283,43,57.61,1,2477.23,2004-08-20,Shipped,3,8,2004,...,23 Tsawassen Blvd.,NaN,Tsawassen,BC,T2F 8M4,Canada,NaN,Lincoln,Elizabeth,Small
2785,10296,21,45.19,10,948.99,2004-09-15,Shipped,3,9,2004,...,Hansastr. 15,NaN,Munich,NaN,80686,Germany,EMEA,Donnermeyer,Michael,Small
2786,10307,34,53.63,4,1823.42,2004-10-14,Shipped,4,10,2004,...,782 First Street,NaN,Philadelphia,PA,71270,USA,NaN,Cervantes,Francisca,Small
2787,10316,34,43.70,12,1485.80,2004-11-01,Shipped,4,11,2004,...,Garden House Crowther Way,NaN,Cowes,Isle of Wight,PO31 7PJ,UK,EMEA,Bennett,Helen,Small
2788,10329,44,86.13,8,3789.72,2004-11-15,Shipped,4,11,2004,...,897 Long Airport Avenue,NaN,NYC,NY,10022,USA,NaN,Yu,Kwai,Medium
2789,10339,27,76.31,6,2060.37,2004-11-23,Shipped,4,11,2004,...,2-2-8 Roppongi,NaN,Minato-ku,Tokyo,106-0032,Japan,Japan,Shimamura,Akiko,Small
2790,10352,49,52.64,4,2579.36,2004-12-03,Shipped,4,12,2004,...,16780 Pompton St.,NaN,Brickhaven,MA,58339,USA,NaN,Taylor,Leslie,Small
2791,10361,23,95.20,12,2189.60,2004-12-17,Shipped,4,12,2004,...,"Monitor Money Building, 815 Pacific Hwy",Level 6,Chatswood,NSW,2067,Australia,APAC,Huxley,Adrian,Small
2792,10373,25,64.97,9,1624.25,2005-01-31,Shipped,1,1,2005,...,Torikatu 38,NaN,Oulu,NaN,90110,Finland,EMEA,Koskitalo,Pirkko,Small
2793,10386,50,87.15,16,4357.50,2005-03-01,Resolved,1,3,2005,...,"C/ Moralzarzal, 86",NaN,Madrid,NaN,28034,Spain,EMEA,Freyre,Diego,Medium
2794,10398,34,40.22,1,1367.48,2005-03-30,Shipped,1,3,2005,...,59 rue de l'Abbaye,NaN,Reims,NaN,51100,France,EMEA,Henriot,Paul,Small
2795,10400,20,56.12,4,1122.40,2005-04-01,Shipped,2,4,2005,...,3086 Ingle Ln.,NaN,San Jose,CA,94217,USA,NaN,Frick,Sue,Small
2796,10415,42,57.61,3,2419.62,2005-05-09,Disputed,2,5,2005,...,7 Allen Street,NaN,Glen Waverly,Victoria,3150,Australia,APAC,Connery,Sean,Small
2797,10105,25,56.78,8,1419.50,2003-02-11,Shipped,1,2,2003,...,Vinb'ltet 34,NaN,Kobenhavn,NaN,1734,Denmark,EMEA,Petersen,Jytte,Small
2798,10117,50,43.68,2,2184.00,2003-04-16,Shipped,2,4,2003,...,"Bronz Sok., Bronz Apt. 3/6 Tesvikiye",NaN,Singapore,NaN,79903,Singapore,Japan,Natividad,Eric,Small
2799,10129,32,64.97,8,2079.04,2003-06-12,Shipped,2,6,2003,...,35 King George,NaN,London,NaN,WX3 6FW,UK,EMEA,Brown,Ann,Small
2800,10142,39,44.23,5,1724.97,2003-08-08,Shipped,3,8,2003,...,5677 Strong St.,NaN,San Rafael,CA,97562,USA,NaN,Nelson,Valarie,Small
2801,10153,50,60.06,4,3003.00,2003-09-28,Shipped,3,9,2003,...,"C/ Moralzarzal, 86",NaN,Madrid,NaN,28034,Spain,EMEA,Freyre,Diego,Medium
2802,10167,38,48.59,15,1846.42,2003-10-23,Cancelled,4,10,2003,...,?kergatan 24,NaN,Boras,NaN,S-844 67,Sweden,EMEA,Larsson,Maria,Small
2803,10177,40,50.23,6,2009.20,2003-11-07,Shipped,4,11,2003,...,"Merchants House, 27-30 Merchant's Quay",NaN,Madrid,NaN,28023,Spain,EMEA,Fernandez,Jesus,Small
2804,10185,28,64.43,6,1804.04,2003-11-14,Shipped,4,11,2003,...,4575 Hillside Dr.,NaN,New Bedford,MA,50553,USA,NaN,Tam,Wing C,Small
2805,10197,42,50.23,12,2109.66,2003-11-26,Shipped,4,11,2003,...,"Rambla de CataluÂ¤a, 23",NaN,Barcelona,NaN,8022,Spain,EMEA,Saavedra,Eduardo,Small
2806,10208,42,63.88,6,2682.96,2004-01-02,Shipped,1,1,2004,...,"2, rue du Commerce",NaN,Lyon,NaN,69004,France,EMEA,Saveley,Mary,Small
2807,10222,36,63.34,18,2280.24,2004-02-19,Shipped,1,2,2004,...,361 Furth Circle,NaN,San Diego,CA,91217,USA,NaN,Thompson,Valarie,Small
2808,10232,24,49.69,3,1192.56,2004-03-20,Shipped,1,3,2004,...,Garden House Crowther Way,NaN,Cowes,Isle of Wight,PO31 7PJ,UK,EMEA,Bennett,Helen,Small
2809,10248,23,65.52,9,1506.96,2004-05-07,Cancelled,2,5,2004,...,897 Long Airport Avenue,NaN,NYC,NY,10022,USA,NaN,Yu,Kwai,Small
2810,10261,29,50.78,7,1472.62,2004-06-17,Shipped,2,6,2004,...,43 rue St. Laurent,NaN,Montreal,Quebec,H1J 1C3,Canada,NaN,Fresnisre,Jean,Small
2811,10273,37,45.86,10,1696.82,2004-07-21,Shipped,3,7,2004,...,Rue Joseph-Bens 532,NaN,Bruxelles,NaN,B-1180,Belgium,EMEA,Dewey,Catherine,Small
2812,10283,33,51.32,12,1693.56,2004-08-20,Shipped,3,8,2004,...,23 Tsawassen Blvd.,NaN,Tsawassen,BC,T2F 8M4,Canada,NaN,Lincoln,Elizabeth,Small
2813,10293,32,60.06,1,1921.92,2004-09-09,Shipped,3,9,2004,...,Via Monte Bianco 34,NaN,Torino,NaN,10100,Italy,EMEA,Accorti,Paolo,Small
2814,10306,35,59.51,6,2082.85,2004-10-14,Shipped,4,10,2004,...,Fauntleroy Circus,NaN,Manchester,NaN,EC2 5NT,UK,EMEA,Ashworth,Victoria,Small
2815,10315,40,55.69,5,2227.60,2004-10-29,Shipped,4,10,2004,...,"67, rue des Cinquante Otages",NaN,Nantes,NaN,44000,France,EMEA,Labrune,Janine,Small
2816,10327,37,86.74,4,3209.38,2004-11-10,Resolved,4,11,2004,...,Vinb'ltet 34,NaN,Kobenhavn,NaN,1734,Denmark,EMEA,Petersen,Jytte,Medium
2817,10337,42,97.16,5,4080.72,2004-11-21,Shipped,4,11,2004,...,5905 Pompton St.,Suite 750,NYC,NY,10022,USA,NaN,Hernandez,Maria,Medium
2818,10350,20,100.00,15,2244.40,2004-12-02,Shipped,4,12,2004,...,"C/ Moralzarzal, 86",NaN,Madrid,NaN,28034,Spain,EMEA,Freyre,Diego,Small
2819,10373,29,100.00,1,3978.51,2005-01-31,Shipped,1,1,2005,...,Torikatu 38,NaN,Oulu,NaN,90110,Finland,EMEA,Koskitalo,Pirkko,Medium
2820,10386,43,100.00,4,5417.57,2005-03-01,Resolved,1,3,2005,...,"C/ Moralzarzal, 86",NaN,Madrid,NaN,28034,Spain,EMEA,Freyre,Diego,Medium
2821,10397,34,62.24,1,2116.16,2005-03-28,Shipped,1,3,2005,...,1 rue Alsace-Lorraine,NaN,Toulouse,NaN,31000,France,EMEA,Roulet,Annette,Small
2822,10414,47,65.52,9,3079.44,2005-05-06,On Hold,2,5,2005,...,8616 Spinnaker Dr.,NaN,Boston,MA,51003,USA,NaN,Yoshido,Juri,Medium

In [12]:
test1.index()

TypeError: 'RangeIndex' object is not callable